### ISSUE TITLE
Creating client with ssh keys gives error --- must be array

### ISSUE THREAD

**Issue by toriacht** [yassirh/digital-ocean-swimmer#36]
Hi,

When adding ssh keys to create-droplet action does not work at present. Server returns error that ssh keys must be an array. This happens if I use one or may ssh keys.

**Comment by yassirh** [comment]
This issue was already fixed in a previous update. can you confirm it please?

**Comment by figlief** [comment]
This problem is still present for me.  Impossible to create droplet with ssh key, same message as in original post.

**Comment by toriacht** [comment]
This works for me now... try below format

HTTP
-------
    POST /v2/droplets HTTP/1.1
    Host: api.digitalocean.com
    Content-Type: application/json
    Authorization: Bearer xxxxxxxxxx
    Cache-Control: no-cache
    
    {"name":"name",
    "region":"lon1",
    "size":"4GB",
    "image":"11111",
    "ssh_keys":["11111"],
    "backups":false,
    "ipv6":true,
    "user_data":null,
    "private_networking":null}
    
or cURL
----------
    curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer 11111" -H "Cache-Control: no-cache" -d '{"name":"name",
    "region":"lon1",
    "size":"4GB",
    "image":"1111",
    "ssh_keys":["1111"],
    "backups":false,
    "ipv6":true,
    "user_data":null,
    "private_networking":null}' 'https://api.digitalocean.com/v2/droplets'

**Comment by yassirh** [comment]
@toriacht i will look into it.

**Comment by rolandstarke** [comment]
Hi,
I get the same error.
What I have done:

Generated the key with juicessh -> copy to clipboard -> paste in the add ssh key dialog (named Roland-Handy) -> create new droplet (test, Ubuntu 12.04.5 x32, Germany, 5$, Roland-Handy)
